### ISSUE TITLE
I have no access to the main menu in mobile viewport

### ISSUE THREAD

**Issue by ghost** [gizmo49/Frontend-designtask#1]
![image](https://user-images.githubusercontent.com/44980164/55864935-5660da80-5b75-11e9-84e6-677ed027120b.png)

**Comment by gizmo49** [comment]
![image](https://user-images.githubusercontent.com/22715960/55875962-53beaf00-5b8e-11e9-984a-9ed1f077bf10.png)

Thank You for noticing,I added a little toggle button for mobile viewports

**Comment by ghost** [comment]
good job
