### ISSUE TITLE
General feedback

### ISSUE THREAD

**Issue by ghost** [gizmo49/Frontend-designtask#4]
I would have preferred to see more semantic tags like `main`, `aside`, `section` etc instead of nested `div`s that make it hard to visualize the different parts of the ui while looking at the code.

Is bootstrap (a quite big library) and jQuery (again still quite big) necessary to achieve this design and interaction? Could we not have found a lighter css reset and utility library for base styles and then vanilla javascript instead of jquery?

Please take this as constructive feedback, you do not need to fix this.

Please fix at least one other issue I've reported prior to this so that I get a chance to see your iterative process.

Thank you for your good work.

**Comment by gizmo49** [comment]
This sure makes sense, as what I have used jquery for can also be done with a few lines too of vanilla Js, This is should occupy top priority for making this more accessible code wise when I try to improve this project, I also might take bootstarp away. what lite css utility library do you recommend?

**Comment by ghost** [comment]
https://tachyons.io/ is nice but there are others, too. The common theme is "css utility libraries"

Thank you for your work on this, we can now close the round on this task. Good job.

**Comment by gizmo49** [comment]
Thank you Serkan.
